{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-03-18T15:40:17Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: release 1.3.0
    sha: 42a6d9e95d4342198dfb8fd0400ee5728b0c0664
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: add variables
    sha: f279758ce857cc7e287a8b29783e85f3e7003563
  - author:
      email: bot@renovateapp.com
      name: Renovate Bot
    branch: master
    committer:
      email: bot@renovateapp.com
      name: Renovate Bot
    message: |
      chore(deps): update dependency io.quarkus:quarkus-maven-plugin to v1.12.2.final
    sha: efb4d04966d1216c2f945fdd4c2e0a7a21891e88
  - author:
      email: bot@renovateapp.com
      name: Renovate Bot
    branch: master
    committer:
      email: bot@renovateapp.com
      name: Renovate Bot
    message: |
      chore(deps): update dependency io.quarkus:quarkus-universe-bom to v1.12.2.final
    sha: eebd27dca5bd404e0dbd42462cd40572ea918177
  - author:
      email: simone@property.xyz
      name: Simone Di Cola
    branch: master
    committer:
      email: simone@property.xyz
      name: Simone Di Cola
    message: |
      feat: add sentry support
    sha: ca3519a017c2fbf0ea44efda6260914e407114ae
  gitHttpUrl: https://github.com/property-xyz/data-yield-stats-service
  gitOwner: property-xyz
  gitRepository: data-yield-stats-service
  name: '{{ .Chart.Name }}'
  releaseNotesURL: https://github.com/property-xyz/data-yield-stats-service/releases/tag/v1.3.1
  version: v1.3.1
status: {}
 
{{- end }}
