{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-11T10:36:00Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: release 1.0.8
    sha: 00f2cba87b63045ebeda6323546b628242892911
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: add variables
    sha: e711428914e8d52715e6157eb8dac6e758c9a9f7
  - author:
      email: simone@property.xyz
      name: Simone Di Cola
    branch: master
    committer:
      email: simone@property.xyz
      name: Simone Di Cola
    message: |
      fix: enable kubernetes config secret
    sha: 832d8ec2eaa30034fb66a9b6f161ab7e78879066
  gitHttpUrl: https://github.com/property-xyz/data-yield-stats-service
  gitOwner: property-xyz
  gitRepository: data-yield-stats-service
  name: '{{ .Chart.Name }}'
  releaseNotesURL: https://github.com/property-xyz/data-yield-stats-service/releases/tag/v1.0.9
  version: v1.0.9
status: {}
 
{{- end }}
