{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-11T10:55:45Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: release 1.0.10
    sha: f109e95843ca07837d109f7f370e7385566696f5
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: add variables
    sha: bbfb7aaa5d0e69fab7b3df45e9b17b4776b90aa1
  - author:
      email: simone@property.xyz
      name: Simone Di Cola
    branch: master
    committer:
      email: simone@property.xyz
      name: Simone Di Cola
    message: |
      fix: role-binding permessions
    sha: 100f550e900da22181a11dc3f50614212dde957d
  gitHttpUrl: https://github.com/property-xyz/data-yield-stats-service
  gitOwner: property-xyz
  gitRepository: data-yield-stats-service
  name: '{{ .Chart.Name }}'
  releaseNotesURL: https://github.com/property-xyz/data-yield-stats-service/releases/tag/v1.0.11
  version: v1.0.11
status: {}
 
{{- end }}
