{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-11T10:15:42Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: release 1.0.6
    sha: 3afdb2877d3db74170317f7f1ef6b9d09917cf56
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: add variables
    sha: 6f2e50b4cf5116e150d04c74c9dcf6a36cdca9b9
  - author:
      email: simone@property.xyz
      name: Simone Di Cola
    branch: master
    committer:
      email: simone@property.xyz
      name: Simone Di Cola
    message: |
      fix: replace deployment name
    sha: e4859028d47eaec191ff7ef1d7ed4affa08d324c
  gitHttpUrl: https://github.com/property-xyz/data-yield-stats-service
  gitOwner: property-xyz
  gitRepository: data-yield-stats-service
  name: '{{ .Chart.Name }}'
  releaseNotesURL: https://github.com/property-xyz/data-yield-stats-service/releases/tag/v1.0.7
  version: v1.0.7
status: {}
 
{{- end }}
