{{- if .Capabilities.APIVersions.Has "jenkins.io/v1/Release" }}
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-09T14:53:24Z"
  deletionTimestamp: null
  name: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
spec:
  commits:
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: release 0.0.6
    sha: 59628fba48f4c4798e4e7d2b7c46c78729755000
  - author:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    branch: master
    committer:
      email: jenkins-x@googlegroups.com
      name: jenkins-x-bot
    message: |
      chore: add variables
    sha: c5e5481f872e3b50eca5fdb866724b75c76300df
  - author:
      email: simone@property.xyz
      name: Simone Di Cola
    branch: master
    committer:
      email: simone@property.xyz
      name: Simone Di Cola
    message: |
      fix: chart version
    sha: 4c5841a96ed2c28413d0d0c72b3fe4d09d6e272b
  gitHttpUrl: https://github.com/property-xyz/data_postcode-yields-service
  gitOwner: property-xyz
  gitRepository: data_postcode-yields-service
  name: '{{ .Chart.Name }}'
  releaseNotesURL: https://github.com/property-xyz/data_postcode-yields-service/releases/tag/v0.0.7
  version: v0.0.7
status: {}
 
{{- end }}
